# ---- build stage ----
FROM node:22-alpine AS builder
WORKDIR /app

RUN apk add --no-cache openssl libc6-compat
RUN corepack enable && corepack prepare pnpm@latest --activate

COPY pnpm-lock.yaml pnpm-workspace.yaml package.json ./
COPY apps/backend/package.json ./apps/backend/package.json
RUN pnpm install --frozen-lockfile --filter ./apps/backend...

COPY apps/backend ./apps/backend

WORKDIR /app/apps/backend
RUN pnpm prisma generate
RUN pnpm build

# ---- run stage ----
FROM node:22-alpine AS runner
WORKDIR /app/apps/backend
ENV NODE_ENV=production

RUN apk add --no-cache openssl libc6-compat
RUN corepack enable && corepack prepare pnpm@latest --activate

COPY pnpm-lock.yaml pnpm-workspace.yaml package.json ./
COPY apps/backend/package.json ./package.json
COPY apps/backend/prisma ./prisma
RUN pnpm install --prod --frozen-lockfile --filter ./apps/backend...

COPY --from=builder /app/apps/backend/dist ./dist
COPY --from=builder /app/node_modules/.pnpm/@prisma+client@*/node_modules/@prisma ./node_modules/@prisma

COPY apps/backend/entrypoint.sh ./entrypoint.sh
RUN chmod +x ./entrypoint.sh

EXPOSE 3000
USER node
ENTRYPOINT ["sh", "./entrypoint.sh"]