name: Build & Deploy

on:
  push:
    branches: [ main ]
    paths:
      - "apps/backend/**"
      - "apps/backend/Dockerfile"
      - "apps/backend/docker-compose.yml"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: [self-hosted, Linux, ARM64]
    steps:
      - uses: actions/checkout@v4
      - name: Login GHCR
        run: docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push (native arm64)
        run: |
          docker build -t ghcr.io/${{ toLower(github.repository) }}:latest -f apps/backend/Dockerfile .
          docker push ghcr.io/${{ toLower(github.repository) }}:latest

      - name: Upload docker-compose
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: "./apps/backend/docker-compose.yml"
          target: "/home/ubuntu/catus/"
          strip_components: 3

      - name: Deploy
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            mkdir -p /home/ubuntu/catus
            echo "${{ secrets.ENV_FILE }}" > /home/ubuntu/catus/.env
            cd /home/ubuntu/catus
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker compose pull api
            docker compose up -d --force-recreate --no-deps api