name: Build & Deploy

on:
  push:
    branches:
      - main
    paths:
      - "apps/backend/**"
      - "apps/backend/Dockerfile"
      - "apps/backend/docker-compose.yml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: apps/backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Docker image
        run: |
          IMAGE=ghcr.io/${{ github.repository }}:latest
          docker build -t $IMAGE .
          docker push $IMAGE

      - name: Upload docker-compose
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: "apps/backend/docker-compose.yml"
          target: "/home/ubuntu/catus/"

      - name: Deploy
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            mkdir -p /home/ubuntu/catus
            echo "${{ secrets.ENV_FILE }}" > /home/ubuntu/catus/.env
            cd /home/ubuntu/catus
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            docker compose pull api
            docker compose up -d --force-recreate --no-deps api